version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pelmeni-db
    environment:
      POSTGRES_DB: pelmeni_db
      POSTGRES_USER: pelmeni_user
      POSTGRES_PASSWORD: pelmeni_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: